baseURL: https://daden.ckep.info

gitRepo: https://github.com/dadenCKEP/dadenCKEP

module:
  imports:
    - path: github.com/hugo-toha/toha/v4

analytics:
  enabled: false

newsletter:
  enable: false