baseURL: https://daden.ckep.info

languageCode: ja-JP
title: dadenCKEP


module:
  imports:
    - path: github.com/hugo-toha/toha/v4
  mounts:
    - source: static/files
      target: static/files

enableEmoji: true
params:
  logo:
    main: /images/logo/ouroboros.png
    invert: /images/logo/ouroboros_invert.png
    favicon: /images/logo/ouroboros.png

  gitRepo: https://github.com/dadenCKEP/dadenCKEP
  gitBranch: src/master

  topNavbar:
    maxVisibleSections: 5

  features:
    darkMode:
      enable: true
      services:
        darkreader:
          defaultColorScheme: system # options are 'system', 'dark', 'light'
          fixes:
            invert: ['img[src$=".svg"]'] # inverts svg colors.
          theme:
            brightness: 100
            contrast: 100
            sepia: 0
    portfolio:
      enable: true
    blog:
      enable: false
    notes:
      enable: false
    comment:
      enable: false
    analytics:
      enabled: false
    support:
      enable: false
    toc:
      enable: false
    tags:
      enable: false
    flags:
      enable: false
    embedpdf:
      enable: false
    flowchart:
      enable: true
      services:
        mermaid:
          theme: dark
    videoPlayer:
      enable: true
      services:
        plyr:
          fullscreen: false
    math:
      enable: false
      services:
        katex:
          delimiters:
            - left: $$
              right: $$
              display: true
            - left: \\[
              right: \\]
              display: true
            - left: $
              right: $
              display: false
            - left: \\(
              right: \\)
              display: false
    syntaxHighlight:
      enable: true
      services:
        hljs:
          noHighlightRe: /^no-highlight$/i
  footer:
    enable: true
    # template: footer.html
    navigation:
      enable: false
      customMenus: false
    contactMe:
      enable: true
    credentials:
      enable: true
    newsletter:
      enable: false
    disclaimer:
      enable: true
